# Site settings
title: Luan Tran
name: Luan Illustrates

# Social Links
social:
  instagram: luan.illust
  facebook:  luanillustrates

# Build settings
host: 0.0.0.0
port: 3000
destination: site
markdown: kramdown
permalink: /luantics/:slug/

paginate: 7
paginate_path: /luantics/:num/

gems:
  - "jekyll-emoji"
  - "jekyll-paginate"

emoji:
  format: emojione-svg       # default html
  ascii: false               # default false
  shortname: true            # default true
  # src: "/assets/imgs/emojis" # defaults to "https://cdn.jsdelivr.net/emojione/assets/#{ext}"

sass:
  sass_dir: assets/css
  style: :nested

# Github pages
# baseurl: /luanillustrates
