#-------------------------------
# General Site Settings

title: Luan Tran
description: Photographer // Illustrator
email: hi@luanillustrates.com

# Social Links
social:
  facebook:  luanillustrates
  instagram: luan.illust

# About Me
accolades:
  - title: Robogals Head of Graphics
    period: 2018 - Present
    url: https://robogals.org


sidebar-menu:
- { name: Portfolio,  url: '/portfolio' }
- { name: LUANtics,   url: '/luantics' }
- { name: About Me,   url: '/about' }
- { name: Let's Talk, url: '/contact' }

overlay-menu:
- { name: Portfolio,  url: '/portfolio', icon: fa-book }
- { name: LUANtics,   url: '/luantics',  icon: fa-newspaper-o }
- { name: About Me,   url: '/about',     icon: fa-user }
- { name: Let's Talk, url: '/contact',   icon: fa-phone }
